export const DASHBOARD_ENUMS = {
  ANALYSIS: {
    ERROR: 0,
    WAITING: 1,
    RUNNING: 2,
    COMPLETED: 3,
  },

  ANALYSIS_OVERRIDE_CRITERIA: {
    CURRENT_FILE: 'current_file',
    ALL_FUTURE_UPLOAD: 'all_future_upload',
  },

  ANALYSIS_STATUS: {
    ERROR: 0,
    WAITING: 1,
    RUNNING: 2,
    COMPLETED: 3,
  },

  APP_ACTION: {
    NO_PREFERENCE: 0,
    HALT: 1,
    PROCEED: 2,
  },

  APP_ENV: {
    NO_PREFERENCE: 0,
    STAGING: 1,
    PRODUCTION: 2,
  },

  CVSS_V3_ATTACK_COMPLEXITY: {
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V3_ATTACK_VECTOR: {
    NETWORK: 'N',
    ADJACENT: 'A',
    LOCAL: 'L',
    PHYSICAL: 'P',
  },

  CVSS_V3_AVAILABILITY_IMPACT: {
    NONE: 'N',
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V3_CONFIDENTIALITY_IMPACT: {
    NONE: 'N',
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V3_INTEGRITY_IMPACT: {
    NONE: 'N',
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V3_PRIVILEGES_REQUIRED: {
    NONE: 'N',
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V3_SCOPE: {
    UNCHANGED: 'U',
    CHANGED: 'C',
  },

  CVSS_V3_USER_INTERACTION: {
    NOT_REQUIRED: 'N',
    REQUIRED: 'R',
  },

  CVSS_V4_ATTACK_COMPLEXITY: {
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V4_ATTACK_REQUIREMENTS: {
    NONE: 'N',
    PRESENT: 'P',
  },

  CVSS_V4_ATTACK_VECTOR: {
    NETWORK: 'N',
    ADJACENT: 'A',
    LOCAL: 'L',
    PHYSICAL: 'P',
  },

  CVSS_V4_PRIVILEGES_REQUIRED: {
    NONE: 'N',
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V4_SUBSEQUENT_AVAILABILITY_IMPACT: {
    NONE: 'N',
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V4_SUBSEQUENT_CONFIDENTIALITY_IMPACT: {
    NONE: 'N',
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V4_SUBSEQUENT_INTEGRITY_IMPACT: {
    NONE: 'N',
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V4_USER_INTERACTION: {
    NONE: 'N',
    PASSIVE: 'P',
    ACTIVE: 'A',
  },

  CVSS_V4_VULN_AVAILABILITY_IMPACT: {
    NONE: 'N',
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V4_VULN_CONFIDENTIALITY_IMPACT: {
    NONE: 'N',
    LOW: 'L',
    HIGH: 'H',
  },

  CVSS_V4_VULN_INTEGRITY_IMPACT: {
    NONE: 'N',
    LOW: 'L',
    HIGH: 'H',
  },

  DEPENDENCY_TYPE: {
    DEPENDENCIES: 1,
    PARENTS: 2,
  },

  DS_AUTOMATED_DEVICE_SELECTION: {
    ANY_DEVICE: 0,
    FILTER_CRITERIA: 1,
  },

  DS_DEVICE_TYPE: {
    NO_PREFERENCE: 0,
    PHONE_REQUIRED: 1,
    TABLET_REQUIRED: 2,
  },

  DS_MANUAL_DEVICE_SELECTION: {
    ANY_DEVICE: 0,
    SPECIFIC_DEVICE: 1,
  },

  DYNAMIC_MODE: {
    MANUAL: 0,
    AUTOMATED: 1,
  },

  DYNAMIC_SCAN_ENGINE: {
    USER_MANUAL: 0,
    AUTOPILOT: 1,
    INTERNAL_MANUAL: 2,
  },

  DYNAMIC_SCAN_STATUS: {
    NOT_STARTED: 0,
    PREPROCESSING: 1,
    PROCESSING_SCAN_REQUEST: 2,
    IN_QUEUE: 3,
    DEVICE_ALLOCATED: 4,
    CONNECTING_TO_DEVICE: 5,
    PREPARING_DEVICE: 6,
    INSTALLING: 7,
    CONFIGURING_API_CAPTURE: 8,
    HOOKING: 9,
    LAUNCHING: 10,
    READY_FOR_INTERACTION: 11,
    DOWNLOADING_AUTOPILOT_SCRIPT: 12,
    CONFIGURING_AUTOPILOT: 13,
    AUTOPILOT_RUNNING: 14,
    AUTOPILOT_COMPLETED: 15,
    STOP_SCAN_REQUESTED: 16,
    SCAN_TIME_LIMIT_EXCEEDED: 17,
    SHUTTING_DOWN: 18,
    CLEANING_DEVICE: 19,
    RUNTIME_DETECTION_COMPLETED: 20,
    ANALYZING: 21,
    ANALYSIS_COMPLETED: 22,
    TIMED_OUT: 23,
    ERROR: 24,
    CANCELLED: 25,
    TERMINATED: 26,
    RETRYING: 27,
  },

  FILE_CAPI_REPORT_STATUS: {
    PENDING: 1,
    STARTED: 2,
    IN_PROGRESS: 3,
    COMPLETED: 4,
    FAILED: 5,
  },

  FILE_DEV_FRAMEWORK: {
    UNKNOWN: -1,
    ANDROID_NATIVE: 0,
    ANDROID_REACT_NATIVE: 1,
    ANDROID_FLUTTER: 2,
    ANDROID_XAMARIN: 3,
    ANDROID_CARDOVA: 4,
    ANDROID_UNKNOWN: 5,
    IOS_NATIVE: 6,
    IOS_SWIFT: 7,
    IOS_REACT_NATIVE: 8,
    IOS_FLUTTER: 9,
    IOS_XAMARIN: 10,
    IOS_CARDOVA: 11,
    IOS_UNKNOWN: 12,
  },

  MANUAL: {
    NONE: 0,
    REQUESTED: 1,
    ASSESSING: 2,
    DONE: 3,
  },

  MFA_METHOD: {
    NONE: 0,
    TOTP: 1,
    HOTP: 2,
  },

  NOTIFY: {
    INFO: 0,
    SUCCESS: 2,
    WARNING: 3,
    ALERT: 4,
    ERROR: 5,
  },

  NOTIF_PRODUCT: {
    APPKNOX: 0,
    STOREKNOX: 1,
  },

  OFFER: {
    NONE: 0,
    CUSTOM: 2,
  },

  ORGANIZATION_ROLES: {
    MEMBER: 0,
    OWNER: 1,
    ADMIN: 2,
  },

  PAYMENT_DURATION: {
    MONTHLY: 1,
    QUARTERLY: 3,
    HALFYEARLY: 6,
    YEARLY: 10,
  },

  PLATFORM: {
    ANDROID: 0,
    IOS: 1,
    WINDOWS: 2,
    BLACKBERRY: 3,
    FIREFOX: 4,
  },

  PRODUCT: {
    APPKNOX: 0,
    DEVKNOX: 1,
  },

  REGULATORY_STATUS: {
    NONE: 0,
    SHOW: 1,
    HIDE: 2,
  },

  RISK: {
    NONE: 0,
    LOW: 1,
    MEDIUM: 2,
    HIGH: 3,
    CRITICAL: 4,
  },

  SBOM_COMPONENT_EXPORT_STATUS: {
    PENDING: 1,
    IN_PROGRESS: 2,
    COMPLETED: 3,
    FAILED: 4,
  },

  SBOM_COMPONENT_TYPE: {
    FRAMEWORK: 0,
    LIBRARY: 1,
    FILE: 2,
    MACHINE_LEARNING_MODEL: 3,
  },

  SCAN_COVERAGE_SCREEN_STATUS: {
    VISITED: 0,
    NOT_VISITED: 1,
  },

  SCAN_COVERAGE_STATUS: {
    NOT_STARTED: 0,
    PROCESSING_DS_EVENTS: 1,
    GENERATING_APP_SCREENS: 2,
    CALCULATING_SCREEN_COVERAGE: 3,
    COMPLETED: 4,
    ERROR: 5,
  },

  SCAN_STATUS: {
    ERROR: 0,
    WAITING: 1,
    RUNNING: 2,
    COMPLETED: 3,
  },

  SCAN_TYPE_FILTER: {
    STATIC_SCAN: 0,
    DYNAMIC_SCAN: 1,
    API_SCAN: 2,
    MANUAL_SCAN: 3,
  },

  SERVICE_NOW_TABLE_SELECTION: {
    SN_VUL_APP_VULNERABLE_ITEM: 1,
    SN_VUL_VULNERABLE_ITEM: 2,
  },

  SUBMISSION_SOURCE: {
    UPLOAD: 0,
    STORE: 1,
    SCM: 2,
  },

  SUBMISSION_STATUS: {
    DOWNLOAD_PREPARE: 0,
    DOWNLOADING: 1,
    DOWNLOAD_FAILED: 2,
    VALIDATE_PREPARE: 3,
    VALIDATING: 4,
    VALIDATE_FAILED: 5,
    ANALYZE_PREPARE: 6,
    ANALYZING: 7,
    STORE_NOT_STARTED: 10100,
    STORE_VALIDATING_URL: 10101,
    STORE_URL_VALIDATION_FAILED: 10102,
    STORE_DOWNLOAD_PREPARE: 10103,
    STORE_DOWNLOADING: 10104,
    STORE_DOWNLOAD_FAILED: 10105,
    STORE_UPLOAD_PREPARE: 10106,
    STORE_UPLOADING: 10107,
    STORE_UPLOAD_FAILED: 10108,
  },

  SUPPORTED_CVSS_VERSIONS: {
    V3: 3,
    V4: 4,
  },

  THRESHOLD: {
    LOW: 1,
    MEDIUM: 2,
    HIGH: 3,
    CRITICAL: 4,
  },

  VULNERABILITY_TYPE: {
    STATIC: 1,
    DYNAMIC: 2,
    MANUAL: 3,
    API: 4,
  },
} as const;
