export const STORE_RELEASE_ENUMS = {
  STORE_RELEASE_FINDING_SEVERITY: {
    BLOCKER: 0,
    WARNING: 1,
  },

  STORE_RELEASE_REPORT_STATUS: {
    PENDING: 1,
    STARTED: 2,
    IN_PROGRESS: 3,
    COMPLETED: 4,
    FAILED: 5,
  },

  STORE_RELEASE_SCAN_STATUS: {
    NOT_STARTED: 0,
    IN_PROGRESS: 1,
    PARTIAL: 2,
    COMPLETED: 3,
    FAILED: 4,
  },

  STORE_RELEASE_VERDICT: {
    HIGH_REJECTION_RISK: 0,
    MODERATE_REJECTION_RISK: 1,
    LOW_REJECTION_RISK: 2,
  },
} as const;
