export const STOREKNOX_ENUMS = {
  SK_APPROVAL_STATUS: {
    PENDING_APPROVAL: 0,
    APPROVED: 1,
    REJECTED: 2,
  },

  SK_APP_MONITORING_STATUS: {
    NOT_FOUND: 0,
    NO_ACTION_NEEDED: 1,
    DISABLED: 2,
    INITIALIZING: 3,
    ACTION_NEEDED: 4,
  },

  SK_APP_MONITORING_STATUS_FILTER: {
    DISABLED: 0,
    NO_ACTION_NEEDED: 1,
    INITIALIZING: 2,
    ACTION_NEEDED: 3,
  },

  SK_APP_STATUS: {
    INACTIVE: 0,
    ACTIVE: 1,
    ARCHIVED: 2,
  },

  SK_AVAILABILITY: {
    VAPT: 0,
    APP_MONITORING: 1,
    NONE: 2,
  },

  SK_DISCOVERY: {
    AUTO: 0,
    MANUAL: 1,
  },

  SK_FAKE_APP_DETECTION_STATUS: {
    DISABLED: 0,
    INITIALIZING: 1,
    NO_RESULTS: 2,
    HAS_RESULTS: 3,
  },

  SK_FAKE_APP_STATUS: {
    PENDING: 0,
    IGNORED: 1,
    ADDED_TO_INVENTORY: 2,
  },

  SK_ORGANIZATION_MEMBERSHIP_ROLES: {
    MEMBER: 1,
    COLLABORATOR: 2,
    ADMIN: 3,
    OWNER: 4,
  },
} as const;
